# Here you can place the packages that will be installed and removed
type: rpm-ostree
repos: 
   - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-39/swayfx-swayfx-fedora-39.repo
install:
   - zsh
  # - swayfx
   - gammastep
   
   # kde stuff
   - dolphin
   - kate
   - ark
   
   # qt
   - qt5-qtgraphicaleffects
   - qt5-qtquickcontrols
   - qt5-qtquickcontrols2
   - qt5-qtwayland
   - qt6-qtwayland
   - qt5ct
   - qt6ct
   - qt5-qtsvg
   - kvantum
   
remove:
 # - sway
 # - sway-config-fedora
   - thunar
   - firefox # default firefox removed in favor of flatpak
   - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
